---
title: Shepherd Scribe
subtitle: Reveries of a Storyteller
description: code and poetry
keywords: stories, code, poetry, algorithms, heart, spirit
author: Cyrus
language: en
timezone: Asia/Manila
url: http://yoursite.com
root: /
permalink: :title/
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: null
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: true
  tab_replace: ""
prismjs:
  enable: false
default_category: uncategorized
category_map:
  Computer-Science: computer-science
  Java: java
  Note: note
  My-Course: course-1
  Theme Shoka Documentation: theme-shoka-doc
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: shokaX
deploy:
  type: git
  repo: https://github.com/shepherdscribe/shepherdscribe.github.io.git
  branch: gh-pages
  message: Site updated
autoprefixer:
  exclude:
    - "*.min.css"
markdown:
  render:
    html: false
    xhtmlOut: true
    breaks: true
    linkify: true
    typographer: null
    quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options:
          tocClassName: toc
          anchorClassName: anchor
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: ()
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: You know too much
minify:
  html:
    enable: true
    stamp: false
    exclude:
      - "**/json.ejs"
      - "**/atom.ejs"
      - "**/rss.ejs"
  css:
    enable: true
    stamp: false
    exclude:
      - "**/*.min.css"
  js:
    enable: true
    stamp: false
    mangle:
      toplevel: true
    output: null
    compress: null
    exclude:
      - "**/*.min.js"
feed:
  limit: 20
  order_by: -date
  tag_dir: false
  category_dir: false
  rss:
    enable: true
    template: themes/shokaX/layout/_alternate/rss.ejs
    output: rss.xml
  atom:
    enable: true
    template: themes/shokaX/layout/_alternate/atom.ejs
    output: atom.xml
  jsonFeed:
    enable: true
    template: themes/shokaX/layout/_alternate/json.ejs
    output: feed.json
